on:
  push:
    branches:
      - master



jobs:
  bulid:
    runs-on: ubuntu-latest

    steps:
      - name: 'testing github action'
                  
        run: pwd

      - name: 'print folder content'
                  
        run: ls 

      - uses: actions/checkout@v3  
      
                  
        
       






        
