on:
  push:
    branches:
      - master



jobs:
  bulid:
    runs-on: ubuntu-latest

    steps:
      

      - uses: actions/checkout@v3  
      - name: "login to dockerhup"
        run: docker login --username ${{secrets.DOCKER_USERNAME }} --password ${{secrets.DOCKER_TOKEN }}
      - name: "Bulding docker image"
        run: docker build -t username ${{secrets.DOCKER_USERNAME }}/nameimage .
      
      - name: "pushing to dockerhub"
        run: docker push  username ${{secrets.DOCKER_USERNAME }}/nameimage 
                  
        
       






        
